CREATE DATABASE chirpy;
USE chirpy;

CREATE TABLE `chirps` (
  id INT NOT NULL AUTO_INCREMENT,
  author VARCHAR(33) NOT NULL,
  chirp VARCHAR(33) NOT NULL,
  time_created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY id;
);